POST  http://localhost:5000/api/auth/register
Content-Type: application/json

{
	"username": "testdb12",
	"password": "testdb"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
	"username": "testdb",
	"password": "testdb"
}

###

POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDkyNjNiNTA5YjdiZTA1M2M5MGZkZjYiLCJpYXQiOjE2MjA3NDQ4NjR9.AuKDLCoqYBSs37_y1LmkD-UwMi9YppXaxMvh1OIVOUY

{
	"title": "hello",
	"description": "test 4",
	"url": "youtube.com/watch?v=rgFd17fyM4A",
	"status": "TO LEARN"
}

###
GET http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDkyNjNiNTA5YjdiZTA1M2M5MGZkZjYiLCJpYXQiOjE2MjAyNzI0NjJ9.hFF-xXbzPUPSqfT8nzY6EReM9YvMpzXtYflU_NkTOHA

###
PUT http://localhost:5000/api/posts/609363e3300f4c09205b261e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDkyNjNiNTA5YjdiZTA1M2M5MGZkZjYiLCJpYXQiOjE2MjAyNzI0NjJ9.hFF-xXbzPUPSqfT8nzY6EReM9YvMpzXtYflU_NkTOHA

{
	"title": "Update post nha",
	"description": "React",
	"url": "facebook.com",
	"status": "LEARNING"
}

###
DELETE http://localhost:5000/api/posts/609363e3300f4c09205b261e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDkyNjNiNTA5YjdiZTA1M2M5MGZkZjYiLCJpYXQiOjE2MjAyNzI0NjJ9.hFF-xXbzPUPSqfT8nzY6EReM9YvMpzXtYflU_NkTOHA

